// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAPz7S5CB3qSk5GBUw0dOtz9O875NS_O5g',
    appId: '1:67391170997:web:16b5f8752694a3be3751fc',
    messagingSenderId: '67391170997',
    projectId: 'ward-clean-54a66',
    authDomain: 'ward-clean-54a66.firebaseapp.com',
    storageBucket: 'ward-clean-54a66.firebasestorage.app',
    measurementId: 'G-WMKJD4V6V7',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBcMVLGT4xijqrtNY1XAbw13TBoXTawMc4',
    appId: '1:67391170997:android:a66adc66743e4fb93751fc',
    messagingSenderId: '67391170997',
    projectId: 'ward-clean-54a66',
    storageBucket: 'ward-clean-54a66.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyA5BNFeNhhp9SIjdM_LGPspDNtBY-VSwPo',
    appId: '1:67391170997:ios:ad309261562c96793751fc',
    messagingSenderId: '67391170997',
    projectId: 'ward-clean-54a66',
    storageBucket: 'ward-clean-54a66.firebasestorage.app',
    iosBundleId: 'com.wardclean.wardclean',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyA5BNFeNhhp9SIjdM_LGPspDNtBY-VSwPo',
    appId: '1:67391170997:ios:ad309261562c96793751fc',
    messagingSenderId: '67391170997',
    projectId: 'ward-clean-54a66',
    storageBucket: 'ward-clean-54a66.firebasestorage.app',
    iosBundleId: 'com.wardclean.wardclean',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAPz7S5CB3qSk5GBUw0dOtz9O875NS_O5g',
    appId: '1:67391170997:web:35fa4966d6c7f50b3751fc',
    messagingSenderId: '67391170997',
    projectId: 'ward-clean-54a66',
    authDomain: 'ward-clean-54a66.firebaseapp.com',
    storageBucket: 'ward-clean-54a66.firebasestorage.app',
    measurementId: 'G-YW1RE6ZGMQ',
  );
}
