// ⚠️ PLACEHOLDER — DO NOT USE AS-IS.
//
// This file must be regenerated by running `flutterfire configure` in the
// project root after you've created a Firebase project and enabled
// Authentication, Firestore, and Storage. See README.md → "Firebase Setup"
// for the exact steps. The CLI will overwrite this file automatically with
// real values for each platform you select (Android/iOS/Web/etc).
//
// Do NOT hand-edit real API keys into this file from memory, and do NOT
// commit a version of this file containing secrets you don't recognize.

import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;

class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    throw UnsupportedError(
      'DefaultFirebaseOptions have not been configured for this project yet.\n'
      'Run: flutterfire configure\n'
      'See README.md for full setup instructions.',
    );
  }
}
